### ISSUE TITLE
LLVM opt crash: multiple definition of local value named 'v_r_2405_3_19_3372'

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#778]
Noticed that one of the failures in #775 seems to be LLVM opt complaining about badly generated LLVM IR:

The following [somewhat] minimised Effekt program:
```scala
import exception

record TestException()

def testException(): Nothing / Exception[TestException] =
  do raise(TestException(), "")

def main() = {
  def defaultTestException { p: => String / Exception[TestException] }: Unit = {
    with on[TestException].default { println("boom") }
    println(p())
  }

  defaultTestException { testException() }
}
```

returns:
```
opt: ./out/repro.ll:916:9: error: multiple definition of local value named 'v_r_2405_3_19_3372'
        %v_r_2405_3_19_3372 = load %Pos, ptr %v_r_2405_3_19_3372_pointer_17, !noalias !2
        ^
```

---

Here's the problematic part of LLVM IR:
```llvm
define tailcc void @returnAddress_15(%Pos %v_r_2405_3_19_3372, %Stack %stack) {
    entry:
        call ccc void @assumeFrameHeaderWasPopped(%Stack %stack)
        %stackPointer_16 = call ccc %StackPointer @stackDeallocate(%Stack %stack, i64 16)
        %v_r_2405_3_19_3372_pointer_17 = getelementptr {%Pos}, %StackPointer %stackPointer_16, i64 0, i32 0
        %v_r_2405_3_19_3372 = load %Pos, ptr %v_r_2405_3_19_3372_pointer_17, !noalias !2 ; !!!!!!!!!!
        call ccc void @erasePositive(%Pos %v_r_2405_3_19_3372)
        
        %pureApp_3399 = call ccc %Pos @println_1(%Pos %v_r_2405_3_19_3372)
        
        %stackPointer_19 = call ccc %StackPointer @stackDeallocate(%Stack %stack, i64 24)
        %returnAddress_pointer_20 = getelementptr %FrameHeader, %StackPointer %stackPointer_19, i64 0, i32 0
        %returnAddress_18 = load %ReturnAddress, ptr %returnAddress_pointer_20, !noalias !2
        musttail call tailcc void %returnAddress_18(%Pos %pureApp_3399, %Stack %stack)
        ret void
}
```

For the record, the Core is OK here.

**Comment by jiribenes** [comment]
Could be relevant to https://github.com/effekt-lang/effekt/pull/741, cc @phischu?

**Comment by serkm** [comment]
Here is the machine IR tree for that function
```
Clause(
        List(Variable(v_r_2405_3_19_3801, Positive())),
        ForeignCall(
          Variable(pureApp_3817, Positive()),
          println_1,
          List(Variable(v_r_2405_3_19_3801, String())),
          Substitute(
            List(
              Tuple2(
                Variable(tmp_3815, Positive()),
                Variable(pureApp_3817, Positive())
              )
            ),
            Return(List(Variable(tmp_3815, Positive())))
          )
        )
      )
```
The variable `v_r_2405_3_19_3801` has `Positive` type at the Parameter declaration and `String` type when used on println.
According to the core IR, both should be of type `String`.

Btw @phischu do we still have a reason to have a separate `String` Type in Machine?

**Comment by phischu** [comment]
Fixed by #785
