### PR TITLE
Fix byte-related LLVM segfaults

### LINKED ISSUE #778: LLVM opt crash: multiple definition of local value named 'v_r_2405_3_19_3372'
Noticed that one of the failures in #775 seems to be LLVM opt complaining about badly generated LLVM IR:

The following [somewhat] minimised Effekt program:
```scala
import exception

record TestException()

def testException(): Nothing / Exception[TestException] =
  do raise(TestException(), "")

def main() = {
  def defaultTestException { p: => String / Exception[TestException] }: Unit = {
    with on[TestException].default { println("boom") }
    println(p())
  }

  defaultTestException { testException() }
}
```

returns:
```
opt: ./out/repro.ll:916:9: error: multiple definition of local value named 'v_r_2405_3_19_3372'
        %v_r_2405_3_19_3372 = load %Pos, ptr %v_r_2405_3_19_3372_pointer_17, !noalias !2
        ^
```

---

Here's the problematic part of LLVM IR:
```llvm
define tailcc void @returnAddress_15(%Pos %v_r_2405_3_19_3372, %Stack %stack) {
    entry:
        call ccc void @assumeFrameHeaderWasPopped(%Stack %stack)
        %stackPointer_16 = call ccc %StackPointer @stackDeallocate(%Stack %stack, i64 16)
        %v_r_2405_3_19_3372_pointer_17 = getelementptr {%Pos}, %StackPointer %stackPointer_16, i64 0, i32 0
        %v_r_2405_3_19_3372 = load %Pos, ptr %v_r_2405_3_19_3372_pointer_17, !noalias !2 ; !!!!!!!!!!
        call ccc void @erasePositive(%Pos %v_r_2405_3_19_3372)
        
        %pureApp_3399 = call ccc %Pos @println_1(%Pos %v_r_2405_3_19_3372)
        
        %stackPointer_19 = call ccc %StackPointer @stackDeallocate(%Stack %stack, i64 24)
        %returnAddress_pointer_20 = getelementptr %FrameHeader, %StackPointer %stackPointer_19, i64 0, i32 0
        %returnAddress_18 = load %ReturnAddress, ptr %returnAddress_pointer_20, !noalias !2
        musttail call tailcc void %returnAddress_18(%Pos %pureApp_3399, %Stack %stack)
        ret void
}
```

For the record, the Core is OK here.

### LINKED ISSUE #783: Segmentation fault (LLVM) using bytearrays
The following program crashes with error code 139 (seg. fault) on the LLVM backend:

```
import bytearray

def onFirst(arr: ByteArray){ action: Byte => Unit }: Unit =
  action(arr.unsafeGet(0))

def main() = {
  var b = bytearray::allocate(1);

  bytearray::fromString("A").onFirst { byte =>
    b.unsafeGet(0)
    println(byte.toInt)
    ()
  }
}
```

<details>
<summary>Address Sanitizer output</summary>

AddressSanitizer:DEADLYSIGNAL
=================================================================
==8056==ERROR: AddressSanitizer: BUS on unknown address (pc 0x64bebebebebebebe bp 0x00016f393a50 sp 0x00016f393a00 T0)
==8056==The signal is caused by a READ memory access.
==8056==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x64bebebebebebebe  (<unknown module>)
    #1 0x0001928b8270  (<unknown module>)

==8056==Register values:
 x[0] = 0x0000000000000010   x[1] = 0x0000603000001c00   x[2] = 0x0000604000000550   x[3] = 0x64bebebebebebebe
 x[4] = 0x0000000000000000   x[5] = 0x0000000000000000   x[6] = 0x0000000000000000   x[7] = 0x0000000000000000
 x[8] = 0x000060c000000201   x[9] = 0x000060c0000001d8  x[10] = 0x0000603000001c00  x[11] = 0x0000000100a71db4
x[12] = 0x0000000000000000  x[13] = 0x0000000000000000  x[14] = 0x0000000000000000  x[15] = 0x0000000000000000
x[16] = 0x0000000192c6e760  x[17] = 0x0000000204b4b898  x[18] = 0x0000000000000000  x[19] = 0x0000602000000110
x[20] = 0x0000604000000510  x[21] = 0x0000604000000550  x[22] = 0x000000016f393b48  x[23] = 0x000000016f393b48
x[24] = 0x00000001928b2000  x[25] = 0x0000000000000000  x[26] = 0x0000000000000000  x[27] = 0x0000000000000000
x[28] = 0x0000000000000000     fp = 0x000000016f393a50     lr = 0x0000000100a72010     sp = 0x000000016f393a00
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS (<unknown module>)
==8056==ABORTING
</details>

This is currently blocking #743, and I would appreciate any help on this issue. Thanks to @jiribenes for minimising the example.

### PR DESCRIPTION
**Pull request by marvinborner**
Closes #783. And closes #778.

I believe the way we currently handle size calculations for stack pushes/pops of non-structural types has some flaws for non-pointer values. Some changes in how we use the GEP instruction will probably fix this, but I find its syntax really confusing. I have a proof-of-concept alternate fix at the end.

To bypass the calculation issues, we can also just change the size of a byte to 8 byte instead. This *hotfix* fixes the segfault in the original issue as well as all of my minified versions.

Some additional explanations of the issue using an example program:

```scala
def foo { action: Byte => Unit }: Unit =
  action(42.toByte)

def main() = {
  foo { b =>
    // does not segfault when printlns are swapped
    println(42)
    println(b)
  }
}
```

<details>

<summary>Pseudo-flow with relevant (for the segfault) lines marked</summary>

```
main(stack)

main(stack):
alloc(3 * 8 = 24)
push returnAddress_1
push sharer_5
push eraser_7
blockLit = vtable[blockLit_3289_clause_13]
foo(blockLit, stack)

foo(blockLit, stack):
alloc(3 * 8 = 24)
push returnAddress_40
push sharer_5
push eraser_7
literal = 42
byte = toByte(literal)
vtable = blockLit[0]
closure = blockLit[1]
fp = *vtable // = blockLit_3289_clause_13
fp(closure, byte, stack)

blockLit_3289_clause_13(closure, byte, stack):
alloc(3 * 8 + 1 = 25) // <---------------------------
push byte
push returnAddress_14
push sharer_26
push eraser_30
literal = 42
printlnInt(literal, stack)

printlnInt(value, stack): // _4
str = show(value)
unit = println(str)
dealloc(3 * 8 = 24)
pop _
pop _
pop returnAddress // _14
returnAddress(unit, stack) // <---------------------------

returnAddress_14(ret, stack):
dealloc(1)
pop byte
erase(ret)
alloc(3 * 8 = 24)
push returnAddress_17
push sharer_5
push eraser_7
printlnByte(byte, stack)

printlnByte(byte, stack):
str = show(byte)
unit = println(str)
dealloc(24)
pop _
pop _
pop returnAddress // _17
returnAddress(unit, stack)

returnAddress_17(unit, stack):
dealloc(24)
pop _
pop _
pop returnAddress // _40
returnAddress(unit, stack)

returnAddress_40(unit, stack)
dealloc(24)
pop _
pop _
pop returnAddress // _1
returnAddress(unit, stack)

returnAddress_1(unit, stack):
dealloc(24)
pop _
pop _
pop returnAddress
returnAddress(unit, stack)
```

</details>

The corresponding LLVM code of the relevant sections:

```llvm
define tailcc void @blockLit_3289_clause_13(%Object %closure, i8 %b_2365, %Stack %stack) {
        
    entry:
        
        ; new blockLit_3289_clause_13, 1 parameters
        %stackPointer_33 = call ccc %StackPointer @stackAllocate(%Stack %stack, i64 25) ; <---------------
        %b_2365_pointer_34 = getelementptr {i8}, %StackPointer %stackPointer_33, i64 0, i32 0
        store i8 %b_2365, ptr %b_2365_pointer_34, !noalias !2
        %returnAddress_pointer_35 = getelementptr {{i8}, %FrameHeader}, %StackPointer %stackPointer_33, i64 0, i32 1, i32 0
        %sharer_pointer_36 = getelementptr {{i8}, %FrameHeader}, %StackPointer %stackPointer_33, i64 0, i32 1, i32 1
        %eraser_pointer_37 = getelementptr {{i8}, %FrameHeader}, %StackPointer %stackPointer_33, i64 0, i32 1, i32 2
        store ptr @returnAddress_14, ptr %returnAddress_pointer_35, !noalias !2
        store ptr @sharer_26, ptr %sharer_pointer_36, !noalias !2
        store ptr @eraser_30, ptr %eraser_pointer_37, !noalias !2
        
        ; literalInt longLiteral_3291, n=42
        %longLiteral_3291 = add i64 42, 0
        
        ; substitution
        
        ; substitution [value_3 !-> longLiteral_3291]
        
        ; jump println_4
        musttail call tailcc void @println_4(i64 %longLiteral_3291, %Stack %stack)
        ret void
}

...

define tailcc void @println_4(i64 %value_3, %Stack %stack) {
        
    entry:
        
        ; definition println_4, environment length 1
        
        ; foreignCall pureApp_3284 : String(), foreign show_14, 1 values
        %pureApp_3284 = call ccc %Pos @show_14(i64 %value_3)
        
        ; foreignCall pureApp_3283 : Positive(), foreign println_1, 1 values
        %pureApp_3283 = call ccc %Pos @println_1(%Pos %pureApp_3284)
        
        ; substitution
        
        ; substitution [v_r_3164_3278 !-> pureApp_3283]
        
        ; return, 1 values
        %stackPointer_56 = call ccc %StackPointer @stackDeallocate(%Stack %stack, i64 24)
        %returnAddress_pointer_57 = getelementptr %FrameHeader, %StackPointer %stackPointer_56, i64 0, i32 0
        %returnAddress_55 = load %ReturnAddress, ptr %returnAddress_pointer_57, !noalias !2
        musttail call tailcc void %returnAddress_55(%Pos %pureApp_3283, %Stack %stack) ; <-------------------------
        ; here is the segfault, since returnAddress_55 is missing one byte!
        ret void
}
```

---

A fix I came up with that does not involve making the size of a byte large:

``` llvm
define tailcc void @blockLit_3289_clause_13(%Object %closure, %Byte %b_2365, %Stack %stack) {
        
    entry:
        ; new blockLit_3289_clause_13, 1 parameters
        ; SPLIT the allocation into two segments <-----------------------
        %stackPointar_33 = call ccc %StackPointer @stackAllocate(%Stack %stack, i64 1)
        %b_2365_pointer_34 = getelementptr %Byte, %StackPointer %stackPointar_33, i64 0
        store %Byte %b_2365, ptr %b_2365_pointer_34, !noalias !2
        
        %stackPointer_33 = call ccc %StackPointer @stackAllocate(%Stack %stack, i64 24)

        %returnAddress_pointer_35 = getelementptr %FrameHeader, %StackPointer %stackPointer_33, i64 0, i32 0
        %sharer_pointer_36 = getelementptr %FrameHeader, %StackPointer %stackPointer_33, i64 0, i32 1
        %eraser_pointer_37 = getelementptr %FrameHeader, %StackPointer %stackPointer_33, i64 0, i32 2
        store ptr @returnAddress_14, ptr %returnAddress_pointer_35, !noalias !2
        store ptr @sharer_26, ptr %sharer_pointer_36, !noalias !2
        store ptr @eraser_30, ptr %eraser_pointer_37, !noalias !2

        ; literalInt longLiteral_3291, n=42
        %longLiteral_3291 = add i64 42, 0
        
        ; substitution
        
        ; substitution [value_3 !-> longLiteral_3291]
        
        ; jump println_4
        musttail call tailcc void @println_4(i64 %longLiteral_3291, %Stack %stack)
        ret void
}

...
```

### CODE REVIEW

**Comment by jiribenes** [comment]
Could y'all check that it also resolves https://github.com/effekt-lang/effekt/issues/778, please?

**Comment by marvinborner** [comment]
Yes, it does :)

**Comment by marvinborner** [comment]
Oh no why did you force push, now my commits are gone

**Review by phischu — APPROVED** [review]

**Comment by marvinborner** [comment]
@phischu why I was advocating for a "proper" fix of the problem, is that LLVM may still sometimes align the bytes in some other way if it feels like it. For example, the following example still segfaults:

```scala
def foo { action: (Byte, Byte) => Unit }: Unit =
  action(42.toByte, 42.toByte)

def main() = {
  foo { (b0, b1) =>
    println(42)
    println(b0)
    println(b1)
  }
}
```

I realize my initial solution is not good and probably annoying to implement in the transformer, but I think we should ultimately solve this in some other way.
